# Generated by Django 4.0 on 2021-12-30 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_name', models.TextField(blank=True)),
                ('date', models.DateField(null=True)),
                ('image', models.URLField(blank=True, null=True)),
                ('link', models.TextField()),
                ('bodytext', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_indonesian', models.TextField(max_length=20)),
                ('search_english', models.TextField(max_length=20)),
            ],
        ),
    ]
